default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: template_development

test:
  <<: *default
  database: template_test
